sonar.projectKey=ErselSeyit_base-station-platform
sonar.organization=erselseyit
sonar.sources=.
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.git/**,**/test-results/**,**/playwright-report/**
sonar.java.source=21
sonar.java.target=21
sonar.sourceEncoding=UTF-8
