{{- if .Values.monitoring.enabled }}
{{- $pt := .Values.monitoring.promtail }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Release.Namespace }}
data:
  promtail.yaml: |
    {{ .Files.Get "files/promtail.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "basestation.labels" (dict "root" . "name" "promtail") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: {{ $pt.image }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          ports:
            - containerPort: {{ $pt.port }}
              name: http-metrics
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml $pt.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
{{- end }}
